rep_dim:
  type: int
  low: 32
  high: 64
lr_g:
  type: loguniform
  low: 1e-4
  high: 1e-2
lr_d:
  type: loguniform
  low: 1e-4
  high: 1e-2
beta_cons:
  type: float
  low: 1.0
  high: 20.0
epochs:
  type: int
  low: 1
  high: 2
