name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        cuda: ["cpu", "cu118"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black ruff
          pip install torch --extra-index-url https://download.pytorch.org/whl/${{ matrix.cuda }}
      - name: Lint
        run: |
          ruff check .
          black --check .
      - name: Run tests
        run: pytest -q
