name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        cuda: ["cpu", "cu118"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            requirements.txt
            .github/workflows/torch-${{ matrix.cuda }}.txt
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install --prefer-binary -r requirements.txt black ruff \
                     torch --extra-index-url https://download.pytorch.org/whl/${{ matrix.cuda }}
      - name: Lint and auto-format
        if: matrix.python-version == '3.12' && matrix.cuda == 'cpu'
        run: |
          ruff check --fix .
          black .
      - name: Push changes back to the branch
        if: github.event_name == 'pull_request' && matrix.python-version == '3.12' && matrix.cuda == 'cpu'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [[ $(git status --porcelain) ]]; then
            git add .
            git commit -m "CI: auto-format Python code with black and ruff"
            git push
          fi
      - name: Run tests
        run: pytest -q
